# Generated by Django 6.0.3 on 2026-03-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('slug', models.SlugField(help_text='الرابط الذي سيظهر في المتصفح', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to=None)),
                ('slug', models.SlugField()),
                ('time', models.TimeField()),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views count')),
            ],
        ),
    ]
