# Generated by Django 5.2.12 on 2026-03-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_category_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AddField(
            model_name='video',
            name='external_thumbnail_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة خارجية'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
