version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=vidblog_db
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=your_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://john:your_password@db:5432/vidblog_db
    depends_on:
      - db

volumes:
  postgres_data: